name: Issue workflow
on:
  issues:
    types: [opened]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo 123
          echo ${{ github.repository }}
